### ISSUE TITLE
can i save the color ascii 

### ISSUE THREAD

**Issue by whisperxd** [qeesung/image2ascii#15]
is there any other option how to save the ascii color text so i can paste it to my bashrc file

**Comment by qeesung** [comment]
For MacOS:
```bash
script -q color.txt image2ascii -f image.jpeg
```

For Linux:
```bash
script -q -c "image2ascii -f image.jpeg" color.txt
```

Finally:
```bash
cat color.txt
```

More detail: https://stackoverflow.com/questions/3515208/can-colorized-output-be-captured-via-shell-redirect
