### ISSUE TITLE
为什么我输入后显示的是乱七八糟的

### ISSUE THREAD

**Issue by guanzenbin** [qeesung/image2ascii#4]
?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;1
6m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;0
0m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;231m ?[0;00m?[38;5;231m ?[0;00m?[38;5;231m ?[0;00m?[38;5;231m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[38;5;16m ?[0;00m?[

**Comment by qeesung** [comment]
如果你是在windows上面，请使用cygwin terminal或者是git bash，windows cmd不支持颜色输出。如果以上两种软件都没有安装，可以disable颜色

```bash
image2ascii -f file.png -c=false  -r 0.2
```
