### ISSUE TITLE
Feature: Option to print raw escape codes of colors

### ISSUE THREAD

**Issue by rafi** [qeesung/image2ascii#7]
It will be really great if image2ascii had an option to print the real escape codes of colors so one could copy/paste the output and place it in a script of his own.

**Comment by qeesung** [comment]
Would you please try this command : 

```bash
image2ascii -f <filename> -w 100 -g 30 > ascii.txt
cat ascii.txt
```
the command would output the ascii with escape codes of colors to the file

**Comment by rafi** [comment]
🤦‍♂️   thanks :D

**Comment by qeesung** [comment]
U are welcome :-)
